# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-18 04:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200, verbose_name='Event Name')),
                ('event_host', models.CharField(max_length=100, verbose_name='Event Host')),
                ('host_email', models.EmailField(max_length=254, verbose_name='Contact Email')),
                ('event_body', models.TextField(verbose_name='Event Description')),
                ('event_date', models.DateField(default=datetime.datetime(2016, 7, 25, 4, 2, 50, 742607), verbose_name='Event Date')),
                ('event_time', models.TimeField(default=datetime.datetime(1900, 1, 1, 23, 59), verbose_name='Event Time')),
                ('event_location', models.CharField(choices=[('1501', '1501'), ('1502', '1502'), ('1503', '1503'), ('1504', '1504'), ('1505', '1505'), ('1506', '1506'), ('1507', '1507'), ('1508', '1508'), ('awing', 'A-Wing Classrooms'), ('bwing', 'B-Wing Classrooms'), ('acpit', 'AC Pit'), ('msarea', 'Math/Study Area'), ('tvpit', 'TV Pit'), ('irc', 'IRC'), ('sodexo', 'Sodexo'), ('oldcafe', 'Old Cafe'), ('science', 'Science Atrium'), ('music', 'Music Wing'), ('union', 'Student Union'), ('lecture', 'Lecture Hall'), ('auditorium', 'Auditorium'), ('mgym', 'Main Gym'), ('wgym', 'West Gym'), ('outside', 'Outside'), ('other', 'Other')], max_length=100, verbose_name='General Location')),
                ('event_specific_location', models.CharField(blank=True, max_length=100, verbose_name='Specific Location')),
                ('display_group', models.CharField(blank=True, max_length=100, verbose_name='Display Group')),
                ('display_fullscreen', models.BooleanField(verbose_name='Display Fullscreen on Club Hub LIVE')),
                ('display_no_slideshow', models.BooleanField(verbose_name="Don't Show on Club Hub LIVE")),
                ('poster_file', models.ImageField(blank=True, upload_to='', verbose_name='Poster File')),
                ('approved', models.BooleanField(verbose_name='Approve event?')),
            ],
        ),
    ]
