# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-18 04:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(default=datetime.datetime(2016, 7, 25, 4, 7, 56, 957174), verbose_name='Event Date'),
        ),
    ]
