# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-18 04:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160718_0407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_time',
        ),
        migrations.AddField(
            model_name='event',
            name='event_datetime',
            field=models.DateField(default=datetime.datetime(2016, 7, 25, 4, 22, 56, 661897), verbose_name='Event Date and Time'),
        ),
    ]
