# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-18 04:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160718_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 25, 4, 45, 51, 587092), verbose_name='Event Date and Time'),
        ),
    ]
