# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 04:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20160718_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 6, 4, 51, 42, 69984), verbose_name='Event Date and Time'),
        ),
    ]
