# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20160730_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_datetime',
            field=models.DateTimeField(verbose_name='Event Date and Time'),
        ),
    ]
