# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20160730_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='poster_file',
            field=models.ImageField(blank=True, upload_to='posters/%Y/%m/%d', verbose_name='Poster File'),
        ),
    ]
