# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20160730_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='display_group',
        ),
        migrations.AddField(
            model_name='event',
            name='allow_custom_html',
            field=models.BooleanField(default=False, help_text='SECURITY WARNING: Enabling this allows the Event Description to be rendered as HTML in Club Hub LIVE,which might disrupt the entire service. Check the description to make sure that it is safe beforeenabling this option.', verbose_name='Allow custom HTML?'),
        ),
        migrations.AlterField(
            model_name='event',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Event approved?'),
        ),
        migrations.AlterField(
            model_name='event',
            name='display_fullscreen',
            field=models.BooleanField(default=False, verbose_name='Display Fullscreen on Club Hub LIVE'),
        ),
        migrations.AlterField(
            model_name='event',
            name='display_no_slideshow',
            field=models.BooleanField(default=False, verbose_name="Don't Show on Club Hub LIVE"),
        ),
        migrations.AlterField(
            model_name='event',
            name='poster_file',
            field=models.ImageField(blank=True, null=True, upload_to='posters/%Y/%m/%d', verbose_name='Poster File'),
        ),
    ]
