# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20160731_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hide_from_registry',
            field=models.BooleanField(default=False, verbose_name="Don't show in the public registry."),
        ),
        migrations.AlterField(
            model_name='event',
            name='allow_custom_html',
            field=models.BooleanField(default=False, help_text='SECURITY WARNING: Enabling this allows the Event Description to be rendered as HTML in Club Hub LIVE, which might disrupt the entire service. Check the description to make sure that it is safe before enabling this option.', verbose_name='Allow custom HTML?'),
        ),
        migrations.AlterField(
            model_name='event',
            name='display_fullscreen',
            field=models.BooleanField(default=False, verbose_name='Display fullscreen on Club Hub LIVE'),
        ),
        migrations.AlterField(
            model_name='event',
            name='display_no_slideshow',
            field=models.BooleanField(default=False, verbose_name="Don't show on Club Hub LIVE"),
        ),
    ]
