# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20160731_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='custom_function',
            field=models.CharField(help_text="SECURITY WARNING: This is only enabled with Custom HTML. This is the designation for this slide's setup and teardown methods. They will be stepfunction_NAME_start() and stepfunction_NAME_teardown().", max_length=32, null=True, verbose_name='Custom Function ID'),
        ),
    ]
