# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_event_custom_function'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slide_duration',
            field=models.IntegerField(default=10000, verbose_name='Club Hub LIVE Slide Duration'),
        ),
    ]
