# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_event_slide_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='custom_function',
            field=models.CharField(blank=True, help_text="SECURITY WARNING: This is only enabled with Custom HTML. This is the designation for this slide's setup and teardown methods. They will be stepfunction_NAME_start() and stepfunction_NAME_teardown().", max_length=32, null=True, verbose_name='Custom Function ID'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slide_duration',
            field=models.IntegerField(default=10000, help_text='Duration of slide on Club Hub LIVE in milleseconds.', verbose_name='Slide Duration'),
        ),
    ]
