# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20160801_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_datetime',
            field=models.DateTimeField(verbose_name='Event Date and Time'),
        ),
    ]
