# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 05:18
from __future__ import unicode_literals

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20160801_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='poster_file',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.get_upload_path, verbose_name='Poster File'),
        ),
    ]
