# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-08 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20160803_0518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Approver Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Approver Email')),
            ],
        ),
    ]
