# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-26 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_approver'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_start_datetime',
            field=models.DateTimeField(help_text='Leave blank and enter an Event End Time for a single-instance event.', null=True, verbose_name='Event Start Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_datetime',
            field=models.DateTimeField(verbose_name='Event End Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_location',
            field=models.CharField(choices=[('1501', '1501'), ('1502', '1502'), ('1503', '1503'), ('1504', '1504'), ('1505', '1505'), ('1506', '1506'), ('1507', '1507'), ('1508', '1508'), ('awing', 'A-Wing Classrooms'), ('bwing', 'B-Wing Classrooms'), ('cac', 'CAC Offices'), ('acpit', 'AC Pit'), ('msarea', 'Math/Study Area'), ('tvpit', 'TV Pit'), ('irc', 'IRC'), ('sodexo', 'Sodexo'), ('oldcafe', 'Old Cafe'), ('science', 'Science Atrium'), ('music', 'Music Wing'), ('union', 'Student Union'), ('lecture', 'Lecture Hall'), ('auditorium', 'Auditorium'), ('mgym', 'Main Gym'), ('wgym', 'West Gym'), ('outside', 'Outside'), ('other', 'Other')], max_length=100, verbose_name='General Location'),
        ),
    ]
