# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-26 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20160826_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='display_fullscreen',
            field=models.BooleanField(default=False, verbose_name='Display poster fullscreen on Club Hub LIVE'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_start_datetime',
            field=models.DateTimeField(blank=True, help_text='Leave blank and enter an Event End Time for a single-instance event.', null=True, verbose_name='Event Start Time'),
        ),
    ]
