# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-26 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20160826_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_start_datetime',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_datetime',
            field=models.DateTimeField(verbose_name='Event End Date/Time'),
        ),
    ]
